/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/anzhi/Desktop/Work/CASE/CASE2021/BaoXinChuang/EF2L15LG100_PRJ/PRJ/al_ip/PLL.v
 ** Date	:	2021 07 24
 ** TD version	:	5.0.27252
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             25.000Mhz
//	Clock multiplication factor: 40
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 7.812500  MHZ	| 0  DEG     
//		C1        	| 15.625000 MHZ	| 0  DEG     
//		C2        	| 31.250000 MHZ	| 0  DEG     
//		C3        	| 62.500000 MHZ	| 0  DEG     
//		C4        	| 125.000000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module PLL(refclk,
		reset,
		extlock,
		clk0_out,
		clk1_out,
		clk2_out,
		clk3_out,
		clk4_out);

	input refclk;
	input reset;
	output extlock;
	output clk0_out;
	output clk1_out;
	output clk2_out;
	output clk3_out;
	output clk4_out;


	EF2_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.DYNCFG("DISABLE"),
		.FIN("25.000"),
		.FEEDBK_MODE("NOCOMP"),
		.FEEDBK_PATH("VCO_PHASE_0"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN(2),
		.ICP_CURRENT(9),
		.KVCO(2),
		.LPF_CAPACITOR(1),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(1),
		.FBCLK_DIV(40),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(128),
		.CLKC0_CPHASE(127),
		.CLKC0_FPHASE(0),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(64),
		.CLKC1_CPHASE(63),
		.CLKC1_FPHASE(0),
		.CLKC2_ENABLE("ENABLE"),
		.CLKC2_DIV(32),
		.CLKC2_CPHASE(31),
		.CLKC2_FPHASE(0),
		.CLKC3_ENABLE("ENABLE"),
		.CLKC3_DIV(16),
		.CLKC3_CPHASE(15),
		.CLKC3_FPHASE(0),
		.CLKC4_ENABLE("ENABLE"),
		.CLKC4_DIV(8),
		.CLKC4_CPHASE(7),
		.CLKC4_FPHASE(0),
		.PU_INTP("DISABLE"),
		.INTPI(0),
		.HIGH_SPEED_EN("DISABLE"),
		.SSC_ENABLE("DISABLE"),
		.SSC_MODE("Down"),
		.SSC_AMP(0.0000),
		.SSC_FREQ_DIV(0),
		.SSC_RNGE(0),
		.FREQ_OFFSET(0.0000),
		.OFFSET_MODE("EXT"),
		.FREQ_OFFSET_INT(0),
		.CLKC0_DUTY(0.5000),
		.CLKC0_DUTY_INT(64),
		.CLKC0_DUTY50("ENABLE"),
		.CLKC1_DUTY(0.5000),
		.CLKC1_DUTY_INT(32),
		.CLKC1_DUTY50("ENABLE")	)
	pll_inst (.refclk(refclk),
		.reset(reset),
		.stdby(1'b0),
		.extlock(extlock),
		.load_reg(1'b0),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(1'b0),
		.dcs(1'b0),
		.dwe(1'b0),
		.di(8'b00000000),
		.daddr(6'b000000),
		.do({open, open, open, open, open, open, open, open}),
		.fbclk(1'b0),
		.clkc({open, open, clk4_out, clk3_out, clk2_out, clk1_out, clk0_out}),
		.ssc_en(1'b0),
		.frac_offset_valid(1'b0),
		.dsm_refclk(1'b0),
		.dsm_rst(reset));

endmodule
